kind: pipeline
type: docker
name: CI_ALICA_API_SPRINGBOOT

variables:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

trigger:
  event:
    - push

steps:
#  - name: build-and-test
#    image: maven:3.8.3
#    commands:
#      - mvn $MAVEN_CLI_OPTS clean compile test

#  - name: code-inspection
#    image: maven
#    secrets: [ API_SPRINGBOOT_SECRET ]
#    environment:
#      sonar_host: http://codefirst.iut.uca.fr/sonar/
#      sonar_token:
#        from_secret: API_SPRINGBOOT_SECRET
#      project_key: ALICA_TEST
#    commands:
#       - mvn clean verify sonar:sonar -Dsonar.login=${sonar_token}

  - name: docker-build-api
    image: plugins/docker
    settings:
      context: .
      dockerfile: Dockerfile
      registry: hub.codefirst.iut.uca.fr
      mirror: https://proxy.iut.uca.fr:8443
      repo: hub.codefirst.iut.uca.fr/sae.alica/api
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD

#    depends_on:
#      - build-and-test

  - name: deploy-container-alica-api
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/sae.alica/api
      CONTAINERNAME: alica-api
      COMMAND: create
      OVERWRITE: true
      ADMINS: baptistedudonne
    depends_on:
      - docker-build-api

#  - name: generate-and-deploy-docs
#    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
#    failure: ignore
#    volumes:
#      - name: docs
#        path: /docs
#    commands:
#      - /entrypoint.sh
