kind: pipeline
type: docker
name: CI_ALICA_API_SPRINGBOOT

variables:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

trigger:
  event:
    - push

steps:
  - name: build
    image: maven:3.8.3
    commands:
      #- mvn clean install
      - mvn $MAVEN_CLI_OPTS compile

  - name: tests
    image: maven:3.8.3
    commands:
      - mvn test

    depends_on: [ build ]

  - name: code-inspection
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_HOST_URL: https://codefirst.iut.uca.fr/sonar/
    secrets: [ API_SPRINGBOOT_SECRET ]
    commands:
      - mvn sonar:sonar -Dsonar.login=$${API_SPRINGBOOT_SECRET}

    depends_on: [ tests ]

  - name: generate-and-deploy-docs
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
    failure: ignore
    volumes:
      - name: docs
        path: /docs
    commands:
      - /entrypoint.sh
